{
 "title": "Cluster",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Fleet tracker observations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fleettrackerinbound_observations[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Traefik public_http",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=\"public_http\",code=~\"^2.+\"}[5m]))",
     "legendFormat": "Success (2xx)"
    },
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=\"public_http\",code=~\"^[4-9].+\"}[5m]))",
     "legendFormat": "Client & server errors (4xx-5xx)"
    }
   ]
  },
  {
   "title": "CPU load5",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "RAM free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{device=\"eth0\"}[5m])",
     "legendFormat": "tx/eth0 on {{instance}}"
    },
    {
     "expr": "irate(node_network_receive_bytes_total{device=\"eth0\"}[5m])",
     "legendFormat": "rx/eth0 on {{instance}}"
    }
   ]
  },
  {
   "title": "Disk space free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/etc/hostname\"}",
     "legendFormat": "{{instance}}, {{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{device=\"vda\"}[5m])",
     "legendFormat": "reads/{{device}} on {{instance}}"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{device=\"vda\"}[5m])",
     "legendFormat": "writes/{{device}} on {{instance}}"
    }
   ]
  },
  {
   "title": "Prometheus head samples",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[5m])",
     "legendFormat": "{instance=\"10.0.0.89:9100\"}"
    }
   ]
  }
 ]
}