{
 "title": "Ruuvit",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Ulkona",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ruuvi_temperature{name=\"Parveke\"}",
     "legendFormat": "Lämpötila"
    },
    {
     "expr": "ruuvi_humidity{name=\"Parveke\"}",
     "legendFormat": "Ilmankosteus"
    }
   ]
  },
  {
   "title": "Ilmankosteus",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "ruuvi_humidity{name=~\"Makuuhuone|Pesuhuone\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Lämpötila sisällä",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ruuvi_temperature{name=~\"Makuuhuone|Pesuhuone\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Ilmanpaine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pressurebar" }
   ],
   "targets": [
    {
     "expr": "ruuvi_pressure{name=\"Parveke\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Paristo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ruuvi_battery{name=~\"Parveke|Makuuhuone|Pesuhuone\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}